version: '3.8'

services:
  # Main application service
  cloud-clipboard:
    images: ghcr.io/qiuyaya/cloud-clipboard:latest
    container_name: cloud-clipboard-app
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - UPLOAD_DIR=/app/uploads
      - MAX_FILE_SIZE=104857600  # 100MB in bytes
      - ROOM_CLEANUP_INTERVAL=3600000  # 1 hour in milliseconds
      - FILE_RETENTION_HOURS=12
      - RATE_LIMIT_WINDOW_MS=60000  # 1 minute
      - RATE_LIMIT_MAX_REQUESTS=100
    volumes:
      - uploads:/app/uploads
      - ./logs:/app/logs
    networks:
      - cloud-clipboard-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp:size=100M,noexec,nosuid,nodev
    user: "1001:1001"

  # Nginx reverse proxy for production deployment
  nginx:
    image: nginx:1.24-alpine
    container_name: cloud-clipboard-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - nginx-cache:/var/cache/nginx
      - nginx-logs:/var/log/nginx
    depends_on:
      - cloud-clipboard
    networks:
      - cloud-clipboard-network
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /var/cache/nginx:size=100M,noexec,nosuid,nodev
      - /var/run:size=10M,noexec,nosuid,nodev

  # Watchtower for automatic updates (optional)
  watchtower:
    image: containrrr/watchtower:latest
    container_name: cloud-clipboard-watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=3600  # Check every hour
      - WATCHTOWER_INCLUDE_RESTARTING=true
    networks:
      - cloud-clipboard-network
    profiles:
      - auto-update

volumes:
  uploads:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data/uploads
  nginx-cache:
    driver: local
  nginx-logs:
    driver: local

networks:
  cloud-clipboard-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16